
name: 'tw_dbt_dev'
version: '0.1'
config-version: 2
profile: 'tw_dbt_dev'
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

models:
  tw_dbt_dev:
      materialized: table
      staging:
        schema: stage
        materialized: view
      mart:
        schema: mart
        core: 
          materialized: incremental
        reporting:
          materilized: view

seeds:
  +schema: seed
  # comment 2