version: 2

models:
  - name: dim_customers
    description: This table has basic information about a customer (Dimension Tables)

    columns:
      - name: customer_key
        description: This is the primary key, generated through Hash

      - name: customer_id
        description: This is a unique identifier for a customer
        tests:
          - unique
          - not_null

      - name: first_name
        description: Customer's first name. PII.

      - name: last_name
        description: Customer's last name. PII.

      - name: email
        description: Customer's email address. PII.

      - name: last_modified_date
        description: Date (UTC) of a customer's information last updated

  - name: fct_orders
    description: This table has basic information about orders (Fact Table of Orders)

    columns:
      - name: order_key
        description: This is the primary key, generated through Hash

      - name: order_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for an order

      - name: customer_key
        description: Foreign key to the customers table
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_key

      - name: order_date
        description: Date (UTC) that the order was placed

      - name: status
        description: '{{ doc("orders_status") }}'
        tests:
          - accepted_values:
              values: ['placed', 'shipped', 'completed', 'return_pending', 'returned']

      - name: last_modified_date
        description: Date (UTC) of a order's information last updated

  - name: fct_payments
    description: This table has basic information about payments (Fact Table of Payments)

    columns:
      - name: payment_key
        description: This is the primary key, generated through Hash

      - name: payment_id
        tests:
          - unique
          - not_null
        description: This is a unique identifier for an payments

      - name: order_key
        description: Payment reference to the order *through Order Key)

      - name: payment_method
        description: Payment Method 
        tests:
          - accepted_values:
              values: ['credit_card', 'coupon', 'bank_transfer', 'gift_card']

      - name: last_modified_date
        description: Date (UTC) of a payment's information last updated

